# Catppuccin Mocha colors for Tmux (Transparent + Powerline)
# Generated by: scripts/regenerate-tmux-theme.sh catppuccin
# Do NOT edit this file directly - edit the script and regenerate

# Theme variables (consumed by tmux.conf and scripts at runtime)
set -g @theme-name "catppuccin"
set -g @theme-bg-dark "#1e1e2e"
set -g @theme-fg-subtle "#6c7086"
set -g @theme-border-inactive "#45475a"
set -g @theme-border-success "#a6e3a1"

# Mode style (copy mode selection)
set -g mode-style "fg=#1e1e2e,bg=#f38ba8,bold"

# Copy mode match highlighting
set -g copy-mode-match-style "fg=#1e1e2e,bg=#a6e3a1"
set -g copy-mode-current-match-style "fg=#1e1e2e,bg=#f38ba8,bold"
set -g copy-mode-mark-style "fg=#1e1e2e,bg=#cba6f7"

# Message style
set -g message-style "fg=#89b4fa,bg=default"
set -g message-command-style "fg=#1e1e2e,bg=#cba6f7,bold"

# --- Pane Border ---
set -g pane-border-lines double
set -g pane-border-style "fg=#45475a,bg=default"
# off: subtle, reload: active, thumbs: info, copy: error, sync: success, prefix: warning, zoom: inactive, default: primary
set -g pane-active-border-style '#{?#{==:#{client_key_table},off},fg=#6c7086 bg=#1e1e2e,#{?#{==:#{@reload_mode},1},fg=#fab387 bg=#1e1e2e,#{?#{==:#{window_name},[thumbs]},fg=#94e2d5 bg=#1e1e2e,#{?pane_in_mode,fg=#f38ba8 bg=#1e1e2e,#{?pane_synchronized,fg=#a6e3a1 bg=#1e1e2e,#{?client_prefix,fg=#f9e2af bg=#1e1e2e,#{?window_zoomed_flag,fg=#cba6f7 bg=#1e1e2e,fg=#89b4fa bg=#1e1e2e}}}}}}}'
set -g pane-border-status top
set -g pane-border-format " #{?@agent_icon,#{?#{||:#{==:#{@agent_status},permission},#{||:#{==:#{@agent_status},hang},#{==:#{@agent_status},error}}},#[fg=colour203]#[bold],#[fg=colour214]#[bold]}#{@agent_icon}#[default] ,}#P: #{?pane_title,#{pane_title},#{pane_current_command}} "
set -g pane-border-indicators both

# --- Window Style ---
set -g window-style 'fg=colour248,bg=default'
set -g window-active-style 'fg=colour255,bg=default'

# --- Status Bar (transparent) ---
set -g status "on"
set -g status-interval 10
set -g status-justify "left"
set -g status-style "fg=#89b4fa,bg=default"

set -g status-left-length "100"
set -g status-right-length "250"

set -g status-left-style NONE
set -g status-right-style NONE

# Left: Session name
set -g status-left "#[fg=#1e1e2e,bg=#f38ba8,bold]  #S #[fg=#f38ba8,bg=default] "

# Right: Prefix押下時はヘルプ、それ以外は通常表示
# 通常表示: [SYSSTAT] [MODE] [GIT] [DATE] [HOST]
# Mode priority: OFF > RELOAD > THUMBS > COPY > SYNC > ZOOM > NORMAL
# Note: カンマは #, でエスケープ（tmux conditional format内で必要）
set -g status-right "#{?client_prefix,#[fg=#f9e2af bg=default]#[fg=#1e1e2e bg=#f9e2af bold]  #[fg=#f9e2af bg=default] -| split  g git  G gh  k keifu  j scratch  f sess  F proj  v copy  r reload  ? keys  Space menu,#[fg=#313244#,bg=default]#[fg=#6c7086#,bg=#313244]#(~/dotfiles/scripts/tmux-cpu.sh)#[fg=#6c7086#,bg=#313244]|#(~/dotfiles/scripts/tmux-ram.sh)#(~/dotfiles/scripts/tmux-gpu.sh)#(~/dotfiles/scripts/tmux-storage.sh)#[fg=#313244#,bg=default] #{?#{==:#{client_key_table},off},#[fg=#6c7086]#[fg=#1e1e2e bg=#6c7086 bold]  OFF #[fg=#6c7086 bg=default],#{?#{==:#{@reload_mode},1},#[fg=#fab387]#[fg=#1e1e2e bg=#fab387 bold]  RELOAD #[fg=#fab387 bg=default],#{?#{==:#{window_name},[thumbs]},#[fg=#94e2d5]#[fg=#1e1e2e bg=#94e2d5 bold] 󰆤 THUMBS #[fg=#94e2d5 bg=default],#{?pane_in_mode,#[fg=#f38ba8]#[fg=#1e1e2e bg=#f38ba8 bold] COPY #[fg=#f38ba8 bg=default],#{?pane_synchronized,#[fg=#a6e3a1]#[fg=#1e1e2e bg=#a6e3a1 bold] SYNC #[fg=#a6e3a1 bg=default],#{?window_zoomed_flag,#[fg=#cba6f7]#[fg=#1e1e2e bg=#cba6f7 bold]  ZOOM #P/#{window_panes} #[fg=#cba6f7 bg=default],#[fg=#89b4fa]#[fg=#1e1e2e bg=#89b4fa] NORMAL #[fg=#89b4fa bg=default]}}}}}}#[fg=#a6e3a1#,bg=default]#[fg=#1e1e2e#,bg=#a6e3a1]  #(cd #{pane_current_path}; git branch --show-current 2>/dev/null || echo '-') #[fg=#a6e3a1#,bg=default]#[fg=#89b4fa#,bg=default]#[fg=#1e1e2e#,bg=#89b4fa]  %m/%d %H:%M #[fg=#89b4fa#,bg=default]#[fg=#89dceb#,bg=default]#[fg=#1e1e2e#,bg=#89dceb#,bold]  #h #[fg=#89dceb#,bg=default]}"

# --- Window Status (Powerline style) ---
setw -g window-status-activity-style "underscore,fg=#cdd6f4,bg=default"
setw -g window-status-separator ""
setw -g window-status-style "NONE,fg=#cdd6f4,bg=default"

# Inactive window (Rounded style) + Claude badge
setw -g window-status-format "#[fg=#45475a,bg=default]#[fg=#cdd6f4,bg=#45475a] #I #W #[fg=#45475a,bg=default]#(~/dotfiles/scripts/tmux-claude-badge.sh window #{window_index} '' #S)"

# Active window (Rounded style with highlight) + Claude badge (dimmed)
setw -g window-status-current-format "#[fg=#89b4fa,bg=default]#[fg=#1e1e2e,bg=#89b4fa,bold] #I #W #[fg=#89b4fa,bg=default]#(~/dotfiles/scripts/tmux-claude-badge.sh window #{window_index} focused #S)"

# Prefix highlight plugin settings (not used, kept for compatibility)
set -g @prefix_highlight_output_prefix ""
set -g @prefix_highlight_output_suffix ""
