# Gruvbox Dark colors for Tmux (Transparent + Powerline)
# Generated by: scripts/regenerate-tmux-theme.sh gruvbox
# Do NOT edit this file directly - edit the script and regenerate

# Theme variables (consumed by tmux.conf and scripts at runtime)
set -g @theme-name "gruvbox"
set -g @theme-bg-dark "#282828"
set -g @theme-fg-subtle "#928374"
set -g @theme-border-inactive "#504945"
set -g @theme-border-success "#b8bb26"

# Mode style (copy mode selection)
set -g mode-style "fg=#282828,bg=#fb4934,bold"

# Copy mode match highlighting
set -g copy-mode-match-style "fg=#282828,bg=#b8bb26"
set -g copy-mode-current-match-style "fg=#282828,bg=#fb4934,bold"
set -g copy-mode-mark-style "fg=#282828,bg=#d3869b"

# Message style
set -g message-style "fg=#83a598,bg=default"
set -g message-command-style "fg=#282828,bg=#d3869b,bold"

# --- Pane Border ---
set -g pane-border-lines double
set -g pane-border-style "fg=#504945,bg=default"
# off: subtle, reload: active, thumbs: info, copy: error, sync: success, prefix: warning, zoom: inactive, default: primary
set -g pane-active-border-style '#{?#{==:#{client_key_table},off},fg=#928374 bg=#282828,#{?#{==:#{@reload_mode},1},fg=#fe8019 bg=#282828,#{?#{==:#{window_name},[thumbs]},fg=#8ec07c bg=#282828,#{?pane_in_mode,fg=#fb4934 bg=#282828,#{?pane_synchronized,fg=#b8bb26 bg=#282828,#{?client_prefix,fg=#fabd2f bg=#282828,#{?window_zoomed_flag,fg=#d3869b bg=#282828,fg=#83a598 bg=#282828}}}}}}}'
set -g pane-border-status top
set -g pane-border-format " #{?@agent_icon,#{?#{||:#{==:#{@agent_status},permission},#{||:#{==:#{@agent_status},hang},#{==:#{@agent_status},error}}},#[fg=colour203]#[bold],#[fg=colour214]#[bold]}#{@agent_icon}#[default] ,}#P: #{?pane_title,#{pane_title},#{pane_current_command}} "
set -g pane-border-indicators both

# --- Window Style ---
set -g window-style 'fg=colour248,bg=default'
set -g window-active-style 'fg=colour255,bg=default'

# --- Status Bar (transparent) ---
set -g status "on"
set -g status-interval 10
set -g status-justify "left"
set -g status-style "fg=#83a598,bg=default"

set -g status-left-length "100"
set -g status-right-length "250"

set -g status-left-style NONE
set -g status-right-style NONE

# Left: Session name
set -g status-left "#[fg=#282828,bg=#fb4934,bold]  #S #[fg=#fb4934,bg=default] "

# Right: Prefix押下時はヘルプ、それ以外は通常表示
# 通常表示: [SYSSTAT] [MODE] [GIT] [DATE] [HOST]
# Mode priority: OFF > RELOAD > THUMBS > COPY > SYNC > ZOOM > NORMAL
# Note: カンマは #, でエスケープ（tmux conditional format内で必要）
set -g status-right "#{?client_prefix,#[fg=#fabd2f bg=default]#[fg=#282828 bg=#fabd2f bold]  #[fg=#fabd2f bg=default] -| split  g git  G gh  k keifu  j scratch  f sess  F proj  v copy  r reload  ? keys  Space menu,#[fg=#3c3836#,bg=default]#[fg=#ff6600#,bg=#3c3836]#(~/dotfiles/scripts/tmux-claude-usage.sh)#[fg=#928374#,bg=#3c3836]|#[fg=#7DD3FC#,bg=#3c3836]#(~/dotfiles/scripts/tmux-codex-usage.sh)#[fg=#928374#,bg=#3c3836]|#[fg=#4285F4#,bg=#3c3836]#(~/dotfiles/scripts/tmux-gemini-usage.sh)#[fg=#928374#,bg=#3c3836]|#[fg=#9966FF#,bg=#3c3836]#(~/dotfiles/scripts/tmux-cursor-usage.sh)#[fg=#928374#,bg=#3c3836]|#(~/dotfiles/scripts/tmux-cpu.sh)#[fg=#928374#,bg=#3c3836]|#(~/dotfiles/scripts/tmux-ram.sh)#(~/dotfiles/scripts/tmux-gpu.sh)#(~/dotfiles/scripts/tmux-storage.sh)#[fg=#3c3836#,bg=default] #{?#{==:#{client_key_table},off},#[fg=#928374]#[fg=#282828 bg=#928374 bold]  OFF #[fg=#928374 bg=default],#{?#{==:#{@reload_mode},1},#[fg=#fe8019]#[fg=#282828 bg=#fe8019 bold]  RELOAD #[fg=#fe8019 bg=default],#{?#{==:#{window_name},[thumbs]},#[fg=#8ec07c]#[fg=#282828 bg=#8ec07c bold] 󰆤 THUMBS #[fg=#8ec07c bg=default],#{?pane_in_mode,#[fg=#fb4934]#[fg=#282828 bg=#fb4934 bold] COPY #[fg=#fb4934 bg=default],#{?pane_synchronized,#[fg=#b8bb26]#[fg=#282828 bg=#b8bb26 bold] SYNC #[fg=#b8bb26 bg=default],#{?window_zoomed_flag,#[fg=#d3869b]#[fg=#282828 bg=#d3869b bold]  ZOOM #P/#{window_panes} #[fg=#d3869b bg=default],#[fg=#83a598]#[fg=#282828 bg=#83a598] NORMAL #[fg=#83a598 bg=default]}}}}}}#[fg=#b8bb26#,bg=default]#[fg=#282828#,bg=#b8bb26]  #(cd #{pane_current_path}; git branch --show-current 2>/dev/null || echo '-') #[fg=#b8bb26#,bg=default]#[fg=#83a598#,bg=default]#[fg=#282828#,bg=#83a598]  %m/%d %H:%M #[fg=#83a598#,bg=default]#[fg=#8ec07c#,bg=default]#[fg=#282828#,bg=#8ec07c#,bold]  #h #[fg=#8ec07c#,bg=default]}"

# --- Window Status (Powerline style) ---
setw -g window-status-activity-style "underscore,fg=#ebdbb2,bg=default"
setw -g window-status-separator ""
setw -g window-status-style "NONE,fg=#ebdbb2,bg=default"

# Inactive window (Rounded style) + Claude badge
setw -g window-status-format "#[fg=#504945,bg=default]#[fg=#d5c4a1,bg=#504945] #I #W #[fg=#504945,bg=default]#(~/dotfiles/scripts/tmux-claude-badge.sh window #{window_index} '' #S)"

# Active window (Rounded style with highlight) + Claude badge (dimmed)
setw -g window-status-current-format "#[fg=#83a598,bg=default]#[fg=#282828,bg=#83a598,bold] #I #W #[fg=#83a598,bg=default]#(~/dotfiles/scripts/tmux-claude-badge.sh window #{window_index} focused #S)"

# Prefix highlight plugin settings (not used, kept for compatibility)
set -g @prefix_highlight_output_prefix ""
set -g @prefix_highlight_output_suffix ""
