# Rose Pine colors for Tmux (Transparent + Powerline)
# Generated by: scripts/regenerate-tmux-theme.sh rosepine
# Do NOT edit this file directly - edit the script and regenerate

# Theme variables (consumed by tmux.conf and scripts at runtime)
set -g @theme-name "rosepine"
set -g @theme-bg-dark "#191724"
set -g @theme-fg-subtle "#6e6a86"
set -g @theme-border-inactive "#403d52"
set -g @theme-border-success "#31748f"

# Mode style (copy mode selection)
set -g mode-style "fg=#191724,bg=#eb6f92,bold"

# Copy mode match highlighting
set -g copy-mode-match-style "fg=#191724,bg=#31748f"
set -g copy-mode-current-match-style "fg=#191724,bg=#eb6f92,bold"
set -g copy-mode-mark-style "fg=#191724,bg=#c4a7e7"

# Message style
set -g message-style "fg=#9ccfd8,bg=default"
set -g message-command-style "fg=#191724,bg=#c4a7e7,bold"

# --- Pane Border ---
set -g pane-border-lines double
set -g pane-border-style "fg=#403d52,bg=default"
# off: subtle, reload: active, thumbs: info, copy: error, sync: success, prefix: warning, zoom: inactive, default: primary
set -g pane-active-border-style '#{?#{==:#{client_key_table},off},fg=#6e6a86 bg=#191724,#{?#{==:#{@reload_mode},1},fg=#ebbcba bg=#191724,#{?#{==:#{window_name},[thumbs]},fg=#9ccfd8 bg=#191724,#{?pane_in_mode,fg=#eb6f92 bg=#191724,#{?pane_synchronized,fg=#31748f bg=#191724,#{?client_prefix,fg=#f6c177 bg=#191724,#{?window_zoomed_flag,fg=#c4a7e7 bg=#191724,fg=#9ccfd8 bg=#191724}}}}}}}'
set -g pane-border-status top
set -g pane-border-format " #P: #{?pane_title,#{pane_title},#{pane_current_command}} "
set -g pane-border-indicators both

# --- Window Style ---
set -g window-style 'fg=colour248,bg=default'
set -g window-active-style 'fg=colour255,bg=default'

# --- Status Bar (transparent) ---
set -g status "on"
set -g status-interval 10
set -g status-justify "left"
set -g status-style "fg=#9ccfd8,bg=default"

set -g status-left-length "100"
set -g status-right-length "250"

set -g status-left-style NONE
set -g status-right-style NONE

# Left: Session name
set -g status-left "#[fg=#191724,bg=#eb6f92,bold]  #S #[fg=#eb6f92,bg=default] "

# Right: Prefix押下時はヘルプ、それ以外は通常表示
# 通常表示: [SYSSTAT] [MODE] [GIT] [DATE] [HOST]
# Mode priority: OFF > RELOAD > THUMBS > COPY > SYNC > ZOOM > NORMAL
# Note: カンマは #, でエスケープ（tmux conditional format内で必要）
set -g status-right "#{?client_prefix,#[fg=#f6c177 bg=default]#[fg=#191724 bg=#f6c177 bold]  #[fg=#f6c177 bg=default] -| split  g git  G gh  k keifu  j scratch  f sess  F proj  v copy  r reload  ? keys  Space menu,#[fg=#26233a#,bg=default]#[fg=#ff6600#,bg=#26233a]#(~/dotfiles/scripts/tmux-claude-usage.sh)#[fg=#6e6a86#,bg=#26233a]|#(~/dotfiles/scripts/tmux-cpu.sh)#[fg=#6e6a86#,bg=#26233a]|#(~/dotfiles/scripts/tmux-ram.sh)#(~/dotfiles/scripts/tmux-gpu.sh)#(~/dotfiles/scripts/tmux-storage.sh)#[fg=#26233a#,bg=default] #{?#{==:#{client_key_table},off},#[fg=#6e6a86]#[fg=#191724 bg=#6e6a86 bold]  OFF #[fg=#6e6a86 bg=default],#{?#{==:#{@reload_mode},1},#[fg=#ebbcba]#[fg=#191724 bg=#ebbcba bold]  RELOAD #[fg=#ebbcba bg=default],#{?#{==:#{window_name},[thumbs]},#[fg=#9ccfd8]#[fg=#191724 bg=#9ccfd8 bold] 󰆤 THUMBS #[fg=#9ccfd8 bg=default],#{?pane_in_mode,#[fg=#eb6f92]#[fg=#191724 bg=#eb6f92 bold] COPY #[fg=#eb6f92 bg=default],#{?pane_synchronized,#[fg=#31748f]#[fg=#191724 bg=#31748f bold] SYNC #[fg=#31748f bg=default],#{?window_zoomed_flag,#[fg=#c4a7e7]#[fg=#191724 bg=#c4a7e7 bold]  ZOOM #P/#{window_panes} #[fg=#c4a7e7 bg=default],#[fg=#9ccfd8]#[fg=#191724 bg=#9ccfd8] NORMAL #[fg=#9ccfd8 bg=default]}}}}}}#[fg=#31748f#,bg=default]#[fg=#191724#,bg=#31748f]  #(cd #{pane_current_path}; git branch --show-current 2>/dev/null || echo '-') #[fg=#31748f#,bg=default]#[fg=#c4a7e7#,bg=default]#[fg=#191724#,bg=#c4a7e7]  %m/%d %H:%M #[fg=#c4a7e7#,bg=default]#[fg=#9ccfd8#,bg=default]#[fg=#191724#,bg=#9ccfd8#,bold]  #h #[fg=#9ccfd8#,bg=default]}"

# --- Window Status (Powerline style) ---
setw -g window-status-activity-style "underscore,fg=#e0def4,bg=default"
setw -g window-status-separator ""
setw -g window-status-style "NONE,fg=#e0def4,bg=default"

# Inactive window (Rounded style) + Claude badge
setw -g window-status-format "#[fg=#403d52,bg=default]#[fg=#e0def4,bg=#403d52] #I #W #[fg=#403d52,bg=default]#(~/dotfiles/scripts/tmux-claude-badge.sh window #{window_index} '' #S)"

# Active window (Rounded style with highlight) + Claude badge (dimmed)
setw -g window-status-current-format "#[fg=#9ccfd8,bg=default]#[fg=#191724,bg=#9ccfd8,bold] #I #W #[fg=#9ccfd8,bg=default]#(~/dotfiles/scripts/tmux-claude-badge.sh window #{window_index} focused #S)"

# Prefix highlight plugin settings (not used, kept for compatibility)
set -g @prefix_highlight_output_prefix ""
set -g @prefix_highlight_output_suffix ""
