[Personal]
source=imaps://kotamatsu05223233%40gmail.com@imap.gmail.com:993
outgoing=smtps+plain://kotamatsu05223233%40gmail.com@smtp.gmail.com:465
default=INBOX
from=松島弘汰 <kotamatsu05223233@gmail.com>
copy-to=Sent
source-cred-cmd=op read "op://Personal/Personal Gmail App/password" 2>/dev/null
outgoing-cred-cmd=op read "op://Personal/Personal Gmail App/password" 2>/dev/null

[SynTopic]
source=imaps://kota.matsushima%40syntopic.io@imap.gmail.com:993
outgoing=smtps+plain://kota.matsushima%40syntopic.io@smtp.gmail.com:465
default=INBOX
from=松島弘汰 <kota.matsushima@syntopic.io>
copy-to=Sent
source-cred-cmd=op read "op://Personal/SynTopic Gmail/password" 2>/dev/null
outgoing-cred-cmd=op read "op://Personal/SynTopic Gmail/password" 2>/dev/null

[UTokyo]
source=imaps://matsukota42274%40g.ecc.u-tokyo.ac.jp@imap.gmail.com:993
outgoing=smtps+plain://matsukota42274%40g.ecc.u-tokyo.ac.jp@smtp.gmail.com:465
default=INBOX
from=松島弘汰 <matsukota42274@g.ecc.u-tokyo.ac.jp>
copy-to=Sent
source-cred-cmd=op read "op://Personal/UTokyo Gmail/password" 2>/dev/null
outgoing-cred-cmd=op read "op://Personal/UTokyo Gmail/password" 2>/dev/null
