[ui]
fuzzy-complete=true
mouse-enabled=true
threading-enabled=true

[compose]
file-picker-cmd=fzf --multi

[filters]
text/plain=colorize
text/calendar=calendar
message/delivery-status=colorize
message/rfc822=colorize
text/html=html | colorize
.headers=colorize
