package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// WorkerMeta は workers/<id>.json。フィールド順は bash jq -n と一致させる
// (crew 所有スキーマなので struct で固定順・byte 安定)。
type WorkerMeta struct {
	ID                string  `json:"id"`
	PaneID            string  `json:"pane_id"`
	ProjectDir        string  `json:"project_dir"`
	WorkerCwd         string  `json:"worker_cwd"`
	Model             string  `json:"model"`
	Started           int64   `json:"started"`
	RestartTimestamps []int64 `json:"restart_timestamps"`
}

// shellQuote は POSIX single-quote quoting (bash に渡す生成文字列用)。
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// hasFixTask は worker が action=fix の task を持つか。
func (c *Crew) hasFixTask(workerID string) bool {
	for _, t := range c.Config.Tasks {
		if t.WorkerID == workerID && t.Action == "fix" {
			return true
		}
	}
	return false
}

// buildHookJSON は Notification(idle_prompt) → idle-hook.sh の設定 (crew 所有、Go で生成)。
// command は bash _start_worker の @sh quoting と等価 (single-quote)。
func (c *Crew) buildHookJSON() string {
	script := filepath.Join(c.StateDir, "bin", "idle-hook.sh")
	command := "bash " + shellQuote(script) + " " + shellQuote(c.StateDir)
	obj := map[string]any{
		"hooks": map[string]any{
			"Notification": []any{
				map[string]any{
					"matcher": "idle_prompt",
					"hooks": []any{
						map[string]any{"type": "command", "command": command},
					},
				},
			},
		},
	}
	b, _ := marshalCompact(obj)
	return b
}

const idleHookScript = `#!/usr/bin/env bash
# Generated by ralph-crew. Do not edit; regenerated on every init.
# Marks the worker associated with the currently-executing Claude TUI pane
# as idle by writing "idle" into its status file. Looks up pane_id in worker
# JSON and updates the matching worker. Safe to run when no worker matches.
set -eu
STATE_DIR="${1:?state_dir required}"
PANE="${TMUX_PANE:-}"
[[ -z "$PANE" ]] && exit 0
shopt -s nullglob
for f in "$STATE_DIR"/workers/*.json; do
  wid="$(jq -r --arg p "$PANE" 'select(.pane_id == $p) | .id // empty' "$f" 2>/dev/null)" || continue
  if [[ -n "$wid" ]]; then
    echo idle > "$STATE_DIR/workers/$wid.status"
    exit 0
  fi
done
`

func (c *Crew) writeIdleHookScript() error {
	p := filepath.Join(c.StateDir, "bin", "idle-hook.sh")
	if err := writeFileString(p, idleHookScript, 0o755); err != nil {
		return err
	}
	return nil
}

// startWorker は bash _start_worker の移植。paneID 空なら restart 経路 (新 window)。
func (c *Crew) startWorker(workerID, paneID string) error {
	w, ok := c.Config.Worker(workerID)
	if !ok {
		errorf("Worker not found in config: %s", workerID)
		return fmt.Errorf("worker not found: %s", workerID)
	}
	model := w.Model
	if model == "" {
		model = "sonnet"
	}
	worktreePath := w.WorktreePath
	if worktreePath == "" {
		worktreePath = c.Config.WorktreePath
	}

	// worker settings + 権限調整 + trust は Claude 所有スキーマなので bash に委譲。
	hookJSON := c.buildHookJSON()
	perms := ""
	if len(w.Permissions) > 0 {
		perms = string(w.Permissions)
	}
	if err := c.setupWorkerSettings(c.ProjectDir, perms, hookJSON, c.hasFixTask(workerID)); err != nil {
		c.logf("worker=%s setup settings failed (continuing): %v", workerID, err)
	}
	infof("Worker settings created: %s/.claude/settings.local.json", c.ProjectDir)

	// system prompt
	spFile := filepath.Join(c.StateDir, "system-prompts", workerID+".txt")
	if w.SystemPrompt != "" {
		if err := writeFileString(spFile, w.SystemPrompt, 0o644); err != nil {
			return err
		}
	}

	// worker_cwd
	workerCwd := c.ProjectDir
	if worktreePath != "" {
		if fi, err := os.Stat(worktreePath); err == nil && fi.IsDir() {
			workerCwd = worktreePath
		} else {
			errorf("worktree_path does not exist: %s (worker: %s)", worktreePath, workerID)
			return fmt.Errorf("worktree missing: %s", worktreePath)
		}
	}

	if err := c.preacceptTrust(workerCwd); err != nil {
		infof("trust pre-accept failed (continuing)")
	}

	// claude command → launch script
	cmd := fmt.Sprintf("claude --model %s --dangerously-skip-permissions", model)
	if w.MCPConfig != "" {
		cmd += " --mcp-config " + shellQuote(w.MCPConfig)
	}
	if w.SystemPrompt != "" {
		cmd += " --append-system-prompt \"$(cat " + shellQuote(spFile) + ")\""
	}
	launch := filepath.Join(c.StateDir, "bin", "launch-"+workerID+".sh")
	launchContent := "#!/usr/bin/env bash\n" +
		"# Generated by ralph-crew. Regenerated on every worker start.\n" +
		"set -eu\n" +
		"cd " + shellQuote(workerCwd) + "\n" +
		"exec " + cmd + "\n"
	if err := writeFileString(launch, launchContent, 0o755); err != nil {
		return err
	}

	// pane 配置
	if paneID == "" {
		windowName := "crew/" + workerID
		if windowExists(c.TmuxSession, windowName) {
			_ = tmuxRun("kill-window", "-t", c.TmuxSession+":"+windowName)
		}
		pid, err := newWindowP(c.TmuxSession, windowName, c.ProjectDir, "bash "+shellQuote(launch))
		if err != nil {
			return fmt.Errorf("new-window: %w", err)
		}
		paneID = pid
	} else {
		if err := respawnPane(paneID, "bash "+shellQuote(launch)); err != nil {
			c.logf("worker=%s respawn-pane failed (continuing)", workerID)
		}
	}
	_ = tmuxRun("select-pane", "-t", paneID, "-T", workerID)

	if !c.waitForTUI(paneID, 30) {
		c.logf("worker=%s timeout waiting for TUI (continuing)", workerID)
	}

	// worker.json (固定順) + status=idle
	meta := WorkerMeta{
		ID: workerID, PaneID: paneID, ProjectDir: c.ProjectDir, WorkerCwd: workerCwd,
		Model: model, Started: nowUnix(), RestartTimestamps: []int64{},
	}
	if err := writeJSONAtomic(filepath.Join(c.workersDir(), workerID+".json"), meta); err != nil {
		return err
	}
	if err := writeFileString(filepath.Join(c.workersDir(), workerID+".status"), "idle", 0o644); err != nil {
		return err
	}
	successf("Started worker: %s (pane: %s)", workerID, paneID)
	return nil
}

// waitForTUI は bash _wait_for_tui: 1s ごとに capture-pane し ❯/>/╭/tips を検出。
func (c *Crew) waitForTUI(paneID string, timeout int) bool {
	for i := 0; i < timeout; i++ {
		time.Sleep(time.Second)
		content, err := tmuxOutput("capture-pane", "-t", paneID, "-p")
		if err != nil {
			continue
		}
		for _, l := range strings.Split(content, "\n") {
			t := strings.TrimSpace(l)
			if strings.Contains(l, "❯") || strings.HasPrefix(t, ">") || strings.HasPrefix(l, "╭") || strings.Contains(l, "tips") {
				return true
			}
		}
	}
	return false
}

// runInit は state dir/tmux session/window/pane を作り worker を spawn する (bash _run_init)。
func (c *Crew) runInit() int {
	for _, d := range []string{"workers", "dispatch", "prompts", "system-prompts", "logs", "bin"} {
		_ = os.MkdirAll(filepath.Join(c.StateDir, d), 0o755)
	}
	if err := c.writeIdleHookScript(); err != nil {
		c.logf("idle-hook write failed: %v", err)
	}
	if hasSession(c.TmuxSession) {
		infof("Session already exists: %s", c.TmuxSession)
	} else {
		if err := tmuxRun("new-session", "-d", "-s", c.TmuxSession, "-n", "control"); err != nil {
			errorf("failed to create tmux session: %v", err)
			return 1
		}
		successf("Created tmux session: %s", c.TmuxSession)
	}

	ppw := c.Config.Layout.PanesPerWindow
	for i, w := range c.Config.Workers {
		windowIdx := i / ppw
		paneIdxInWindow := i % ppw
		windowName := fmt.Sprintf("crew-%02d", windowIdx+1)

		var paneID string
		var err error
		if paneIdxInWindow == 0 {
			if windowExists(c.TmuxSession, windowName) {
				_ = tmuxRun("kill-window", "-t", c.TmuxSession+":"+windowName)
			}
			paneID, err = newWindowP(c.TmuxSession, windowName, c.ProjectDir)
		} else {
			paneID, err = splitWindowP(c.TmuxSession+":"+windowName, c.ProjectDir)
			_ = tmuxRun("select-layout", "-t", c.TmuxSession+":"+windowName, "tiled")
		}
		if err != nil {
			c.logf("worker=%s pane create failed: %v", w.ID, err)
			continue
		}
		if err := c.startWorker(w.ID, paneID); err != nil {
			c.logf("worker=%s start failed: %v", w.ID, err)
		}
	}
	n := len(c.Config.Workers)
	successf("Initialized %d worker(s) in session: %s (panes_per_window=%d)", n, c.TmuxSession, ppw)
	c.logf("init completed: %d workers, panes_per_window=%d", n, ppw)
	return 0
}
