#!/bin/bash

# JankyBorders configuration
# Color matches sketchybar accent color

borders active_color=0xff0055bb \
        inactive_color=0x00000000 \
        width=8.0 \
        style=round \
        hidpi=on
