#!/bin/bash
# tmux テーマファイルを再生成（powerline文字を正しいバイトで埋め込む）
# Linux環境でgit clone後に角丸が表示されない場合に使用
#
# 重要: tokyonight.tmux を直接編集せず、このスクリプトを編集して再生成すること
# powerline文字がgit操作で破損する可能性があるため

set -euo pipefail

TARGET="${1:-$HOME/.config/tmux/tokyonight.tmux}"

# Powerline / Nerd Font characters (UTF-8 bytes)
LEFT=$(printf '\xee\x82\xb6')    # U+E0B6 - left rounded
RIGHT=$(printf '\xee\x82\xb4')   # U+E0B4 - right rounded
GIT_ICON=$(printf '\xee\x82\xa0')   # U+E0A0 - git branch
CLOCK_ICON=$(printf '\xef\x80\x97') # U+F017 - clock
USER_ICON=$(printf '\xef\x80\x87')  # U+F007 - user

cat > "$TARGET" << EOF
# TokyoNight Night colors for Tmux (Transparent + Powerline)
# Generated by: scripts/regenerate-tmux-theme.sh
# Do NOT edit this file directly - edit the script and regenerate

# Mode style (copy mode selection - red to match border)
set -g mode-style "fg=#1a1b26,bg=#f7768e,bold"

# Copy mode match highlighting
set -g copy-mode-match-style "fg=#1a1b26,bg=#9ece6a"
set -g copy-mode-current-match-style "fg=#1a1b26,bg=#f7768e,bold"
set -g copy-mode-mark-style "fg=#1a1b26,bg=#bb9af7"

# Message style
set -g message-style "fg=#7aa2f7,bg=default"
set -g message-command-style "fg=#1a1b26,bg=#bb9af7,bold"

# Pane border (dynamic color based on mode)
set -g pane-border-style "fg=#3b4261"
# copy mode: 赤, sync: ティール, 通常: 青
set -g pane-active-border-style "#{?pane_in_mode,fg=#f7768e,#{?pane_synchronized,fg=#73daca,fg=#7aa2f7}}"

# Status bar (transparent)
set -g status "on"
set -g status-interval 2
set -g status-justify "left"
set -g status-style "fg=#7aa2f7,bg=default"

set -g status-left-length "100"
set -g status-right-length "250"

set -g status-left-style NONE
set -g status-right-style NONE

# Left: Session name (桃色 #f7768e、左端は角丸なし)
set -g status-left "#[fg=#1a1b26,bg=#f7768e,bold]  #S #[fg=#f7768e,bg=default]${RIGHT} "

# Right: Custom mode indicator + Git branch, Date, Time, Hostname
# Mode indicator: copy=red, sync=teal, prefix=yellow, normal=blue
set -g status-right "#{?pane_in_mode,#[fg=#f7768e]${LEFT}#[fg=#1a1b26 bg=#f7768e bold] COPY #[fg=#f7768e bg=default]${RIGHT},#{?pane_synchronized,#[fg=#73daca]${LEFT}#[fg=#1a1b26 bg=#73daca bold] SYNC #[fg=#73daca bg=default]${RIGHT},#{?client_prefix,#[fg=#e0af68]${LEFT}#[fg=#1a1b26 bg=#e0af68 bold] PREFIX #[fg=#e0af68 bg=default]${RIGHT},#[fg=#7aa2f7]${LEFT}#[fg=#1a1b26 bg=#7aa2f7] NORMAL #[fg=#7aa2f7 bg=default]${RIGHT}}}}\\
#[fg=#9ece6a,bg=default]${LEFT}#[fg=#1a1b26,bg=#9ece6a] ${GIT_ICON} #(cd #{pane_current_path}; git branch --show-current 2>/dev/null || echo '-') #[fg=#9ece6a,bg=default]${RIGHT}\\
#[fg=#7aa2f7,bg=default]${LEFT}#[fg=#1a1b26,bg=#7aa2f7] ${CLOCK_ICON} %m/%d %H:%M #[fg=#7aa2f7,bg=default]${RIGHT}\\
#[fg=#7dcfff,bg=default]${LEFT}#[fg=#1a1b26,bg=#7dcfff,bold] ${USER_ICON} #h #[fg=#7dcfff,bg=default]"

# Window status (Powerline style)
setw -g window-status-activity-style "underscore,fg=#a9b1d6,bg=default"
setw -g window-status-separator ""
setw -g window-status-style "NONE,fg=#a9b1d6,bg=default"

# Inactive window (Rounded style) + Claude badge
setw -g window-status-format "#[fg=#3b4261,bg=default]${LEFT}#[fg=#a9b1d6,bg=#3b4261] #I #W #[fg=#3b4261,bg=default]${RIGHT}#(~/dotfiles/scripts/tmux-claude-badge.sh window #{window_index})"

# Active window (Rounded style with highlight) + Claude badge (dimmed)
setw -g window-status-current-format "#[fg=#7aa2f7,bg=default]${LEFT}#[fg=#1a1b26,bg=#7aa2f7,bold] #I #W #[fg=#7aa2f7,bg=default]${RIGHT}#(~/dotfiles/scripts/tmux-claude-badge.sh window #{window_index} focused)"

# Prefix highlight plugin settings (not used, kept for compatibility)
set -g @prefix_highlight_output_prefix ""
set -g @prefix_highlight_output_suffix ""
EOF

echo "Generated: $TARGET"
echo "Run: tmux source ~/.config/tmux/tmux.conf"
